INSERT INTO PERSON VALUES (1,'Ahmed Khan')
INSERT INTO PERSON VALUES (2,'Ali Raza')
INSERT INTO PERSON VALUES (3,'Usman Tariq')
INSERT INTO PERSON VALUES (4,'Hassan Shah')
INSERT INTO PERSON VALUES (5,'Bilal Ahmed')
INSERT INTO PERSON VALUES (6,'Saad Malik')
INSERT INTO PERSON VALUES (7,'Hamza Ali')
INSERT INTO PERSON VALUES (8,'Talha Khan')
INSERT INTO PERSON VALUES (9,'Zain Abbas')
INSERT INTO PERSON VALUES (10,'Omer Farooq')
INSERT INTO PERSON VALUES (11,'Ayesha Noor')
INSERT INTO PERSON VALUES (12,'Fatima Khan')
INSERT INTO PERSON VALUES (13,'Sara Ahmed')
INSERT INTO PERSON VALUES (14,'Maryam Ali')
INSERT INTO PERSON VALUES (15,'Hina Tariq')

SELECT COUNT(*) FROM PERSON

SELECT * FROM PERSON

INSERT INTO PERSON_PHONE VALUES (1,'03001111111')
INSERT INTO PERSON_PHONE VALUES (2,'03002222222')
INSERT INTO PERSON_PHONE VALUES (3,'03003333333')
INSERT INTO PERSON_PHONE VALUES (4,'03004444444')
INSERT INTO PERSON_PHONE VALUES (5,'03005555555')
INSERT INTO PERSON_PHONE VALUES (6,'03006666666')
INSERT INTO PERSON_PHONE VALUES (7,'03007777777')
INSERT INTO PERSON_PHONE VALUES (8,'03008888888')
INSERT INTO PERSON_PHONE VALUES (9,'03009999999')
INSERT INTO PERSON_PHONE VALUES (10,'03101111111')
INSERT INTO PERSON_PHONE VALUES (11,'03102222222')
INSERT INTO PERSON_PHONE VALUES (12,'03103333333')
INSERT INTO PERSON_PHONE VALUES (13,'03104444444')
INSERT INTO PERSON_PHONE VALUES (14,'03105555555')
INSERT INTO PERSON_PHONE VALUES (15,'03106666666')

SELECT COUNT(*) FROM PERSON_PHONE

SELECT * FROM PERSON_PHONE

INSERT INTO MEMBERSHIP_PLAN VALUES (1,'Basic',1,3000)
INSERT INTO MEMBERSHIP_PLAN VALUES (2,'Silver',3,8000)
INSERT INTO MEMBERSHIP_PLAN VALUES (3,'Gold',6,15000)
INSERT INTO MEMBERSHIP_PLAN VALUES (4,'Premium',12,25000)
INSERT INTO MEMBERSHIP_PLAN VALUES (5,'VIP',12,40000)

SELECT COUNT(*) FROM MEMBERSHIP_PLAN

SELECT * FROM MEMBERSHIP_PLAN

INSERT INTO TRAINER VALUES (1,1,'Weight Training')
INSERT INTO TRAINER VALUES (2,2,'Cardio')
INSERT INTO TRAINER VALUES (3,3,'Body Building')
INSERT INTO TRAINER VALUES (4,4,'CrossFit')
INSERT INTO TRAINER VALUES (5,5,'Yoga')

SELECT COUNT(*) FROM TRAINER

SELECT * FROM TRAINER

INSERT INTO NUTRITIONIST VALUES (1,11,'BS Nutrition')
INSERT INTO NUTRITIONIST VALUES (2,12,'MS Dietetics')
INSERT INTO NUTRITIONIST VALUES (3,13,'Clinical Nutrition')

SELECT COUNT(*) FROM NUTRITIONIST

SELECT * FROM NUTRITIONIST

INSERT INTO MEMBER VALUES (1,6,'saad@gmail.com','REGULAR',1)
INSERT INTO MEMBER VALUES (2,7,'hamza@gmail.com','PREMIUM',4)
INSERT INTO MEMBER VALUES (3,8,'talha@gmail.com','REGULAR',2)
INSERT INTO MEMBER VALUES (4,9,'zain@gmail.com','PREMIUM',5)
INSERT INTO MEMBER VALUES (5,10,'omer@gmail.com','REGULAR',3)

SELECT COUNT(*) FROM MEMBER

SELECT * FROM MEMBER

INSERT INTO REGULAR_MEMBER VALUES (1,'Gym Access')
INSERT INTO REGULAR_MEMBER VALUES (3,'Gym Access')
INSERT INTO REGULAR_MEMBER VALUES (5,'Gym Access')

SELECT COUNT(*) FROM REGULAR_MEMBER

SELECT * FROM REGULAR_MEMBER

INSERT INTO PREMIUM_MEMBER VALUES (2,'Diet Plan + Personal Trainer','Trainer 1')
INSERT INTO PREMIUM_MEMBER VALUES (4,'VIP Access','Trainer 2')

SELECT COUNT(*) FROM PREMIUM_MEMBER

SELECT * FROM PREMIUM_MEMBER

INSERT INTO WORKOUT_SESSION VALUES (1,'Morning Cardio',TO_DATE('2026-06-01','YYYY-MM-DD'),'08:00 AM',2)
INSERT INTO WORKOUT_SESSION VALUES (2,'Strength Training',TO_DATE('2026-06-02','YYYY-MM-DD'),'10:00 AM',1)
INSERT INTO WORKOUT_SESSION VALUES (3,'CrossFit Session',TO_DATE('2026-06-03','YYYY-MM-DD'),'06:00 PM',4)

SELECT COUNT(*) FROM WORKOUT_SESSION

SELECT * FROM WORKOUT_SESSION

INSERT INTO EQUIPMENT VALUES (1,'Treadmill','Cardio',5)
INSERT INTO EQUIPMENT VALUES (2,'Dumbbells','Strength',20)
INSERT INTO EQUIPMENT VALUES (3,'Bench Press','Strength',4)
INSERT INTO EQUIPMENT VALUES (4,'Exercise Bike','Cardio',3)
INSERT INTO EQUIPMENT VALUES (5,'Yoga Mat','Flexibility',15)

SELECT COUNT(*) FROM EQUIPMENT

SELECT * FROM EQUIPMENT

INSERT INTO SESSION_EQUIPMENT VALUES (1,1,2)
INSERT INTO SESSION_EQUIPMENT VALUES (2,2,10)
INSERT INTO SESSION_EQUIPMENT VALUES (2,3,2)
INSERT INTO SESSION_EQUIPMENT VALUES (3,5,10)

SELECT COUNT(*) FROM SESSION_EQUIPMENT

SELECT * FROM SESSION_EQUIPMENT

INSERT INTO ATTENDANCE VALUES (1,1,1,'PRESENT')
INSERT INTO ATTENDANCE VALUES (2,2,1,'ABSENT')
INSERT INTO ATTENDANCE VALUES (3,3,2,'PRESENT')
INSERT INTO ATTENDANCE VALUES (4,4,2,'PRESENT')
INSERT INTO ATTENDANCE VALUES (5,5,3,'ABSENT')

SELECT COUNT(*) FROM ATTENDANCE

SELECT * FROM ATTENDANCE

INSERT INTO ASSIGNED_TRAINER VALUES (1,1)
INSERT INTO ASSIGNED_TRAINER VALUES (2,2)
INSERT INTO ASSIGNED_TRAINER VALUES (3,3)
INSERT INTO ASSIGNED_TRAINER VALUES (4,4)
INSERT INTO ASSIGNED_TRAINER VALUES (5,5)

SELECT COUNT(*) FROM ASSIGNED_TRAINER

SELECT * FROM ASSIGNED_TRAINER

INSERT INTO INVOICE VALUES (1,1,TO_DATE('2026-06-01','YYYY-MM-DD'),3000)
INSERT INTO INVOICE VALUES (2,2,TO_DATE('2026-06-01','YYYY-MM-DD'),25000)
INSERT INTO INVOICE VALUES (3,3,TO_DATE('2026-06-02','YYYY-MM-DD'),8000)
INSERT INTO INVOICE VALUES (4,4,TO_DATE('2026-06-02','YYYY-MM-DD'),40000)
INSERT INTO INVOICE VALUES (5,5,TO_DATE('2026-06-03','YYYY-MM-DD'),15000)

SELECT COUNT(*) FROM INVOICE

SELECT * FROM INVOICE

INSERT INTO DIET_PLAN VALUES (1,1,'Weight Loss Diet')
INSERT INTO DIET_PLAN VALUES (2,2,'Muscle Gain Diet')
INSERT INTO DIET_PLAN VALUES (3,3,'Balanced Nutrition Plan')

SELECT COUNT(*) FROM DIET_PLAN

SELECT * FROM DIET_PLAN

INSERT INTO FEEDBACK VALUES (1,1,'Excellent Trainer',TO_DATE('2026-06-05','YYYY-MM-DD'))
INSERT INTO FEEDBACK VALUES (2,2,'Very Good Session',TO_DATE('2026-06-05','YYYY-MM-DD'))
INSERT INTO FEEDBACK VALUES (3,3,'Equipment Needs Upgrade',TO_DATE('2026-06-06','YYYY-MM-DD'))

SELECT COUNT(*) FROM FEEDBACK

SELECT * FROM FEEDBACK
















