CREATE TABLE PERSON (
    PERSON_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE PERSON_PHONE (
    PERSON_ID NUMBER,
    PHONE VARCHAR2(15),
    PRIMARY KEY (PERSON_ID, PHONE),
    FOREIGN KEY (PERSON_ID)
    REFERENCES PERSON(PERSON_ID)
    ON DELETE CASCADE
);

CREATE TABLE MEMBERSHIP_PLAN (
    PLAN_ID NUMBER PRIMARY KEY,
    PLAN_NAME VARCHAR2(50) NOT NULL UNIQUE,
    DURATION_MONTHS NUMBER NOT NULL,
    FEE NUMBER(10,2) NOT NULL CHECK (FEE > 0)
);

CREATE TABLE MEMBER (
    MEMBER_ID NUMBER PRIMARY KEY,
    PERSON_ID NUMBER UNIQUE,
    EMAIL VARCHAR2(100) UNIQUE,
    MEMBERSHIP_TYPE VARCHAR2(20)
        CHECK (MEMBERSHIP_TYPE IN ('REGULAR','PREMIUM')),
    PLAN_ID NUMBER NOT NULL,

    FOREIGN KEY (PERSON_ID)
    REFERENCES PERSON(PERSON_ID),

    FOREIGN KEY (PLAN_ID)
    REFERENCES MEMBERSHIP_PLAN(PLAN_ID)
);

CREATE TABLE REGULAR_MEMBER (
    MEMBER_ID NUMBER PRIMARY KEY,
    BASIC_FEATURES VARCHAR2(200),

    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER(MEMBER_ID)
    ON DELETE CASCADE
);

CREATE TABLE PREMIUM_MEMBER (
    MEMBER_ID NUMBER PRIMARY KEY,
    EXTRA_FEATURES VARCHAR2(200),
    PERSONAL_TRAINER VARCHAR2(100),

    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER(MEMBER_ID)
    ON DELETE CASCADE
);

CREATE TABLE TRAINER (
    TRAINER_ID NUMBER PRIMARY KEY,
    PERSON_ID NUMBER UNIQUE,
    SPECIALTY VARCHAR2(100),

    FOREIGN KEY (PERSON_ID)
    REFERENCES PERSON(PERSON_ID)
);

CREATE TABLE NUTRITIONIST (
    NUTRITIONIST_ID NUMBER PRIMARY KEY,
    PERSON_ID NUMBER UNIQUE,
    QUALIFICATION VARCHAR2(100),

    FOREIGN KEY (PERSON_ID)
    REFERENCES PERSON(PERSON_ID)
);

CREATE TABLE WORKOUT_SESSION (
    SESSION_ID NUMBER PRIMARY KEY,
    SESSION_NAME VARCHAR2(100) NOT NULL,
    SESSION_DATE DATE,
    SESSION_TIME VARCHAR2(20),
    TRAINER_ID NUMBER,

    FOREIGN KEY (TRAINER_ID)
    REFERENCES TRAINER(TRAINER_ID)
);

CREATE TABLE EQUIPMENT (
    EQUIPMENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    TYPE VARCHAR2(50),
    QUANTITY NUMBER DEFAULT 0
);

CREATE TABLE SESSION_EQUIPMENT (
    SESSION_ID NUMBER,
    EQUIPMENT_ID NUMBER,
    QUANTITY NUMBER,

    PRIMARY KEY (SESSION_ID, EQUIPMENT_ID),

    FOREIGN KEY (SESSION_ID)
    REFERENCES WORKOUT_SESSION(SESSION_ID),

    FOREIGN KEY (EQUIPMENT_ID)
    REFERENCES EQUIPMENT(EQUIPMENT_ID)
);

CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER,
    SESSION_ID NUMBER,

    STATUS VARCHAR2(10)
    CHECK (STATUS IN ('PRESENT','ABSENT')),

    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER(MEMBER_ID),

    FOREIGN KEY (SESSION_ID)
    REFERENCES WORKOUT_SESSION(SESSION_ID)
);

CREATE TABLE ASSIGNED_TRAINER (
    MEMBER_ID NUMBER,
    TRAINER_ID NUMBER,

    PRIMARY KEY (MEMBER_ID, TRAINER_ID),

    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER(MEMBER_ID),

    FOREIGN KEY (TRAINER_ID)
    REFERENCES TRAINER(TRAINER_ID)
);

CREATE TABLE INVOICE (
    INVOICE_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER,
    INVOICE_DATE DATE,
    AMOUNT NUMBER(10,2)
    CHECK (AMOUNT > 0),

    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE DIET_PLAN (
    DIET_ID NUMBER PRIMARY KEY,
    NUTRITIONIST_ID NUMBER,
    PLAN_DETAILS VARCHAR2(500),

    FOREIGN KEY (NUTRITIONIST_ID)
    REFERENCES NUTRITIONIST(NUTRITIONIST_ID)
);

CREATE TABLE FEEDBACK (
    FEEDBACK_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER,
    COMMENTS VARCHAR2(500),
    FEEDBACK_DATE DATE,

    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER(MEMBER_ID)
);























